spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:helianthus}
    username: ${POSTGRES_USER:helianthus}
    password: ${POSTGRES_PASSWORD:helianthus}
    driver-class-name: org.postgresql.Driver
