package helianthus.core.catalog

import helianthus.core.access.SqlDialect
import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Pins the SQL generated by [EntityCrudSqlBuilder] for list and get-by-id
 * operations, including field selection, aliasing, filters, ordering, and
 * pagination through a stubbed [SqlDialect].
 */
class EntityCrudSqlBuilderTest {

    private val dialect = object : SqlDialect {
        override fun quoteIdentifier(name: String): String = "\"$name\""
        override fun limitOffset(limit: Int, offset: Int): String = "LIMIT $limit OFFSET $offset"
    }
    private val builder = EntityCrudSqlBuilder(dialect)

    private fun createEntity(
        table: String = "products",
        primaryKey: PrimaryKeyDef = PrimaryKeyDef("id"),
        fields: List<String> = listOf("id", "name", "price")
    ) = EntityDef(
        datasource = "default",
        table = table,
        primaryKey = primaryKey,
        fields = fields.map { FieldDef(it) }
    )

    private fun createEntityWithFieldDefs(
        table: String = "products",
        primaryKey: PrimaryKeyDef = PrimaryKeyDef("id"),
        fields: List<FieldDef> = listOf(FieldDef("id"), FieldDef("name"), FieldDef("price"))
    ) = EntityDef(
        datasource = "default",
        table = table,
        primaryKey = primaryKey,
        fields = fields
    )

    @Test
    fun `buildListSql should generate basic select without filters`() {
        val entity = createEntity()

        val plan = builder.buildListSql(
            entity = entity,
            filters = emptyMap(),
            orderBy = null,
            orderDir = "ASC",
            limit = 100,
            offset = 0
        )

        assertTrue(plan.sql.contains("SELECT"))
        assertTrue(plan.sql.contains("\"id\""))
        assertTrue(plan.sql.contains("\"name\""))
        assertTrue(plan.sql.contains("\"price\""))
        assertTrue(plan.sql.contains("FROM \"products\""))
        assertTrue(plan.sql.contains("LIMIT 100"))
        assertTrue(plan.sql.contains("OFFSET 0"))
        assertEquals(0, plan.params.size)
    }

    @Test
    fun `buildListSql should generate select with filters`() {
        val entity = createEntity()

        val plan = builder.buildListSql(
            entity = entity,
            filters = mapOf("name" to "Widget"),
            orderBy = null,
            orderDir = "ASC",
            limit = 100,
            offset = 0
        )

        assertTrue(plan.sql.contains("WHERE"))
        assertTrue(plan.sql.contains("\"name\" = ?"))
        assertEquals(1, plan.params.size)
        assertEquals("Widget", plan.params[0].value)
    }

    @Test
    fun `buildListSql should generate select with multiple filters`() {
        val entity = createEntity()

        val plan = builder.buildListSql(
            entity = entity,
            filters = mapOf("name" to "Widget", "price" to 50.0),
            orderBy = null,
            orderDir = "ASC",
            limit = 100,
            offset = 0
        )

        assertTrue(plan.sql.contains("WHERE"))
        assertTrue(plan.sql.contains("\"name\" = ?"))
        assertTrue(plan.sql.contains("\"price\" = ?"))
        assertTrue(plan.sql.contains("AND"))
        assertEquals(2, plan.params.size)
    }

    @Test
    fun `buildListSql should generate select with orderBy`() {
        val entity = createEntity()

        val plan = builder.buildListSql(
            entity = entity,
            filters = emptyMap(),
            orderBy = "name",
            orderDir = "DESC",
            limit = 100,
            offset = 0
        )

        assertTrue(plan.sql.contains("ORDER BY \"name\" DESC"))
    }

    @Test
    fun `buildListSql should ignore orderBy if not in fields`() {
        val entity = createEntity()

        val plan = builder.buildListSql(
            entity = entity,
            filters = emptyMap(),
            orderBy = "nonexistent",
            orderDir = "ASC",
            limit = 100,
            offset = 0
        )

        assertTrue(!plan.sql.contains("ORDER BY"))
    }

    @Test
    fun `buildListSql should ignore filters not in fields`() {
        val entity = createEntity()

        val plan = builder.buildListSql(
            entity = entity,
            filters = mapOf("nonexistent" to "value"),
            orderBy = null,
            orderDir = "ASC",
            limit = 100,
            offset = 0
        )

        assertTrue(!plan.sql.contains("WHERE"))
        assertEquals(0, plan.params.size)
    }

    @Test
    fun `buildListSql should generate select with limit and offset`() {
        val entity = createEntity()

        val plan = builder.buildListSql(
            entity = entity,
            filters = emptyMap(),
            orderBy = null,
            orderDir = "ASC",
            limit = 50,
            offset = 100
        )

        assertTrue(plan.sql.contains("LIMIT 50"))
        assertTrue(plan.sql.contains("OFFSET 100"))
    }

    @Test
    fun `buildGetByIdSql should generate select with primary key filter`() {
        val entity = createEntity()

        val plan = builder.buildGetByIdSql(entity, "123")

        assertTrue(plan.sql.contains("SELECT"))
        assertTrue(plan.sql.contains("FROM \"products\""))
        assertTrue(plan.sql.contains("WHERE \"id\" = ?"))
        assertEquals(1, plan.params.size)
        assertEquals("123", plan.params[0].value)
    }

    @Test
    fun `buildGetByIdSql should handle numeric id`() {
        val entity = createEntity()

        val plan = builder.buildGetByIdSql(entity, 456L)

        assertEquals(1, plan.params.size)
        assertEquals(456L, plan.params[0].value)
    }

    @Test
    fun `buildGetByIdSql should use first column of composite primary key`() {
        val entity = createEntity(
            primaryKey = PrimaryKeyDef(listOf("orderId", "lineNumber")),
            fields = listOf("orderId", "lineNumber", "product")
        )

        val plan = builder.buildGetByIdSql(entity, "100")

        assertTrue(plan.sql.contains("WHERE \"orderId\" = ?"))
        assertEquals(1, plan.params.size)
    }

    @Test
    fun `buildListSql should emit unquoted column AS quoted name alias when they differ`() {
        val entity = createEntityWithFieldDefs(
            primaryKey = PrimaryKeyDef("productCode"),
            fields = listOf(
                FieldDef("productCode", "productcode"),
                FieldDef("productLine", "productline")
            )
        )

        val plan = builder.buildListSql(entity, emptyMap(), null, "ASC", 100, 0)

        assertTrue(plan.sql.contains("""productcode AS "productCode""""))
        assertTrue(plan.sql.contains("""productline AS "productLine""""))
    }

    @Test
    fun `buildListSql should not alias when name equals column`() {
        val entity = createEntityWithFieldDefs(
            primaryKey = PrimaryKeyDef("id"),
            fields = listOf(FieldDef("id", "id"), FieldDef("name", "name"))
        )

        val plan = builder.buildListSql(entity, emptyMap(), null, "ASC", 100, 0)

        assertTrue(plan.sql.contains("\"id\""))
        assertTrue(!plan.sql.contains("""AS "id""""))
    }

    @Test
    fun `buildListSql should use unquoted physical column in WHERE filter when name differs`() {
        val entity = createEntityWithFieldDefs(
            primaryKey = PrimaryKeyDef("productCode"),
            fields = listOf(
                FieldDef("productCode", "productcode"),
                FieldDef("productLine", "productline")
            )
        )

        val plan = builder.buildListSql(entity, mapOf("productLine" to "Classic Cars"), null, "ASC", 100, 0)

        assertTrue(plan.sql.contains("productline = ?"))
        assertTrue(!plan.sql.contains(""""productLine" = ?"""))
    }

    @Test
    fun `buildListSql should use unquoted physical column in ORDER BY when name differs`() {
        val entity = createEntityWithFieldDefs(
            primaryKey = PrimaryKeyDef("productCode"),
            fields = listOf(
                FieldDef("productCode", "productcode"),
                FieldDef("productName", "productname")
            )
        )

        val plan = builder.buildListSql(entity, emptyMap(), "productName", "DESC", 100, 0)

        assertTrue(plan.sql.contains("ORDER BY productname DESC"))
        assertTrue(!plan.sql.contains("""ORDER BY "productName""""))
    }

    @Test
    fun `buildGetByIdSql should use unquoted physical column in WHERE when name differs`() {
        val entity = createEntityWithFieldDefs(
            primaryKey = PrimaryKeyDef("productCode"),
            fields = listOf(
                FieldDef("productCode", "productcode"),
                FieldDef("productName", "productname")
            )
        )

        val plan = builder.buildGetByIdSql(entity, "S10_1678")

        assertTrue(plan.sql.contains("WHERE productcode = ?"))
        assertTrue(!plan.sql.contains("""WHERE "productCode" = ?"""))
        assertTrue(plan.sql.contains("""productcode AS "productCode""""))
    }

    @Test
    fun `buildListSql ClassicModels products generates correct alias SQL`() {
        val strategy = LowercaseNamingStrategy()
        val entity = createEntityWithFieldDefs(
            table = "products",
            primaryKey = PrimaryKeyDef("productCode"),
            fields = listOf("productCode", "productName", "productLine", "buyPrice", "quantityInStock")
                .map { FieldDef(it, strategy.toPhysicalColumn(it)) }
        )

        val plan = builder.buildListSql(entity, emptyMap(), null, "ASC", 100, 0)

        assertTrue(plan.sql.contains("""productcode AS "productCode""""))
        assertTrue(plan.sql.contains("""productname AS "productName""""))
        assertTrue(plan.sql.contains("""productline AS "productLine""""))
        assertTrue(plan.sql.contains("""buyprice AS "buyPrice""""))
        assertTrue(plan.sql.contains("""quantityinstock AS "quantityInStock""""))
    }

    @Test
    fun `buildListSql should quote all identifiers`() {
        val entity = createEntity(
            table = "my-table",
            fields = listOf("my-id", "my-name")
        )

        val plan = builder.buildListSql(
            entity = entity,
            filters = mapOf("my-name" to "test"),
            orderBy = "my-id",
            orderDir = "ASC",
            limit = 10,
            offset = 0
        )

        assertTrue(plan.sql.contains("\"my-table\""))
        assertTrue(plan.sql.contains("\"my-id\""))
        assertTrue(plan.sql.contains("\"my-name\""))
    }

    @Test
    fun `buildListSql should handle empty entity fields gracefully`() {
        val entity = createEntity(fields = emptyList())

        val plan = builder.buildListSql(
            entity = entity,
            filters = emptyMap(),
            orderBy = null,
            orderDir = "ASC",
            limit = 100,
            offset = 0
        )

        assertTrue(plan.sql.contains("SELECT"))
        assertTrue(plan.sql.contains("FROM \"products\""))
    }
}
